# Directories will be set in a locals file, not the config

steps = ["source_find", "photometry"]
targets = ["ngc1097"]
product = ["anchor"]
bands = ["F200W"]
version = ["v4p1"]
ptype = ["images"]

[parameters.source_find]

# Background subtraction
sigma_to_clip = 3.0
coverage_mask = false
box_size = 50
filter_size = 3
bkg_estimator = 'SExtractorBackground()'

# Source finding
do_source_find = true
finder = 'iraf'
snr_threshold = 3.0
use_filter_fwhm = false
fwhm = 2.0
roundlo = -0.5
roundhi = 0.5
sharplo = 0.2
sharphi = 1.0
nsources = 50000


[parameters.photometry]

use_brightest = false
aperture_radius = 3
phot_method = 'exact'
radius_sky_in = 5
radius_sky_out = 10
sigma_to_cip = 3.0
maxiters = 5