# Directories will be set in a locals file, not the config

steps = ["source_find", "photometry"]
targets = ["ngc1097", "ngc1512"]
product = ["anchor"]
bands = ["F200W"]
version = 'v4p1'
ptype = ["images"]
projects = ["4793"]

[parameters.r_opt]

max_r = 20
brightest_ropt = 50
frac = 0.95
plot = true

[parameters.bkg_subtract]

sigma = 3.0
coverage_mask = false
box_size = 50
filter_size = 3
bkg_estimator = 'SExtractorBackground()'

[parameters.source_find]

finder = 'iraf'
snr_threshold = 3.0
fwhm = 2.0
roundlo = -0.5
roundhi = 0.5
sharplo = 0.2
sharphi = 1.0
nsources = 50000


[parameters.photometry]

use_brightest = false
aperture_radius = 3
phot_method = 'exact'
radius_sky_in = 5
radius_sky_out = 10
sigma_to_cip = 3.0
maxiters = 5
write = false